INSERT INTO soluble_fiber_lists(foodstuff_name, soluble_fiber) VALUES
    ('ワカメ', 5.0),
    ('ニンニク', 4.1),
    ('ユリネ', 3.3),
    ('ユズ', 3.3),
    ('オートミール', 3.2),
    ('ナットウ', 2.3),
    ('ゴボウ', 2.3),
    ('レモン', 2.0),
    ('モズク', 2.0),
    ('メカブ', 2.0),